kubernetes-sigs/cloud-provider-huaweicloud

go.mod
=> Initial go module

cmd/cloud-controller-manager/cloud-controller-manager.go
According to [developing cloud controller manager](https://kubernetes.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/), add main function.
=> Set up ccm main function

cmd/cloud-controller-manager/cloud-controller-manager.go, pkg/cloudprovider/huaweicloud/huaweicloud.go
Provided `HuaweiCloud` to implements `cloudprovider.Interface`.
=> Set up base architecture of ccm

go.mod
=> tidy modules

go.mod, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/huaweicloud_test.go, pkg/cloudprovider/huaweicloud/loadbalancer.go, pkg/cloudprovider/huaweicloud/testdata/valid-cloud-provider.json
/kind feature
Add cloud provider configuration definition.
Fixes #
```release-note
NONE
```
=> Add cloud provider configuration definition

pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/loadbalancer.go
/kind feature
Fixes #
```release-note
NONE
```
=> Implements LoadBalancer interface

examples/loadbalancers/secret.yaml, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/loadbalancer.go
Add a secret example and some minor comments.
Fixes #
```release-note
NONE
```
=> Add secret example and comments

examples/loadbalancers/secret.yaml, pkg/cloudprovider/huaweicloud/testdata/valid-cloud-provider.json
Minor change.
Fixes #
```release-note
NONE
```
=> Update example secrect name to follow name rule

go.mod, go.sum, pkg/cloudprovider/huaweicloud/clusters.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/loadbalancer.go, pkg/cloudprovider/huaweicloud/routes.go, pkg/cloudprovider/huaweicloud/zone.go
/kind feature
Add dummy implementation of cloudprovider.Interface.
```release-note
NONE
```
=> Pr implement dummy interfaces

hack/verify-gofmt.sh
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Skip vendor code when verify gofmt

pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go
/kind feature
Add a new file `instance.go` to encapsulates the implementation of cloudprovider.Instances.
Fixes #
```release-note
NONE
```
```docs
```
=> Split instances functionality out

pkg/cloudprovider/huaweicloud/config.go, pkg/cloudprovider/huaweicloud/config_test.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/testdata/valid-cloud-provider.json
/kind feature
Propose a new config file.
Fixes #
```release-note
NONE
```
```docs
```
=> Proposal of new config file

.travis.yml, Makefile
/kind cleanup
Fixes #35 
```release-note
NONE
```
```docs
```
=> integrate unit test

pkg/cloudprovider/huaweicloud/huaweicloud.go
/kind feature
Fixes #
```release-note
Legacy load balance config format has been refactored.
```
```docs
```
=> Update legacy loadbalancer according to new config format.

go.mod, go.sum, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/instances_test.go, vendor/github.com/mitchellh/mapstructure/.travis.yml, vendor/github.com/mitchellh/mapstructure/CHANGELOG.md, vendor/github.com/mitchellh/mapstructure/LICENSE, vendor/github.com/mitchellh/mapstructure/README.md, vendor/github.com/mitchellh/mapstructure/decode_hooks.go, vendor/github.com/mitchellh/mapstructure/error.go, vendor/github.com/mitchellh/mapstructure/go.mod, vendor/github.com/mitchellh/mapstructure/mapstructure.go, vendor/modules.txt
/kind feature
implement instance NodeAddressesByProviderID.
Fixes #
```release-note
NONE
```
```docs
```
=> implement instance NodeAddressesByProviderID 

pkg/cloudprovider/huaweicloud/instances.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Implement instances InstanceExistsByProviderID

pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/instances_test.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Implement instances InstanceTypeByProviderID

pkg/cloudprovider/huaweicloud/instances.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Postpone interface NodeAddresses

pkg/cloudprovider/huaweicloud/instances.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Postpone instance interface InstanceType

pkg/cloudprovider/huaweicloud/instances.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> implement instance InstanceShutdownByProviderID

pkg/cloudprovider/huaweicloud/instances.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Postpone instance InstanceID interface

README.md
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Add a initial Readme

README.md, code-of-conduct.md, docs/CloudControllerManagerConfiguration.md, examples/CloudControllerManagerConfigurationExample.json
Fixes #
```release-note
NONE
```
```docs
```
=> Add document about configuration

OWNERS
/kind cleanup
Add OWNER files.
Fixes #
```release-note
NONE
```
```docs
```
=> Add owner files

.gitignore, Makefile, cluster/images/cloud-controller-manager/Dockerfile
/kind cleanup
Fixes #47 
```release-note
NONE
```
```docs
```
=> Add default docker file

Makefile
/kind feature
Add a new endpoint to makefile to support image upload.
Fixes #47 
```release-note
NONE
```
```docs
```
=> Add upload images to makefile

pkg/cloudprovider/huaweicloud/huaweicloud.go
/kind bug
Fix a panic that when delete a secret in cache.
Fixes #
```release-note
NONE
```
```docs
```
=> Fix a panic when try to delete a secret in cache

docs/example-manifests/huawei-cloud-controller-manager.yaml
Fixes #
```release-note
NONE
```
```docs
```
=> Add ccm manifests

docs/resources/service/README.md, docs/resources/service/annotations.md, pkg/cloudprovider/huaweicloud/huaweicloud.go
Fixes #
```release-note
NONE
```
```docs
```
=> Pr add docs services

docs/example-manifests/etcd.yaml, docs/example-manifests/kube-apiserver.yaml, docs/example-manifests/kube-scheduler.yaml
Fixes #
```release-note
NONE
```
```docs
```
=> Add manifests of kube components

README.md, docs/config/CloudControllerManagerConfiguration.md, docs/quick-start-with-local-cluster.md
Fixes #
```release-note
NONE
```
=> add quick start with local cluster

docs/quick-start-with-local-cluster.md
/kind cleanup
Minor change. Just update outdated link.
Fixes #
```release-note
NONE
```
=> Fix outdated link

cmd/cloud-controller-manager/cloud-controller-manager.go, go.mod, pkg/cloudprovider/huaweicloud/http.go
/kind cleanup
Update module  name.
Fixes #63 
```release-note
NONE
```
=> Update module prefix from k8s.io to sigs.k8s.io

README.md
/kind cleanup
Fixes #64 
```release-note
NONE
```
=> Updated all docs and replace huawei-cloudnative/ with kubernetes-sigs/

pkg/cloudprovider/huaweicloud/huaweicloud.go
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind cleanup
Fixes #71
@RainbowMango 
None
=> remove useless function

docs/config/CloudControllerManagerConfiguration.md, pkg/cloudprovider/huaweicloud/config.go
Fixed broken links.
Fixes #
```release-note
NONE
```
```docs
```
=> fix broken links

go.sum, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/instances_test.go
/kind feature
This PR implements the cloud provider `InstanceID` method that is called by the [node controller](https://github.com/kubernetes/kubernetes/blob/3a51aaf8b4baff1242ea30b08d599d913fe7a127/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L522). This allows the users of this CCM not to specify the `provider-id` kubelet flag.
Fixes #74 
```release-note
```
```docs
```
=> Implement instanceID method

examples/loadbalancers/secret.yaml, pkg/cloudprovider/huaweicloud/instances_test.go
This PR fixes the example secret used for authentication with the ELB endpoint:
- Use correct data field names
- Uses base64 encoded values, having plaintext values could be misleading.
Fixes #
```release-note
```
```docs
```
=> Fix example secret

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md
Add issue templates.
Fixes #
```release-note
NONE
```
=> Add issue template

pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/instances_test.go
/kind feature
This PR just migrated  `cloudprovider.Instances` interface `InstanceID` to SDK V3.
Refer #84 
```release-note
NONE
```
=> Migrate Instances.InstanceID interface with SDK V3

pkg/cloudprovider/huaweicloud/instances.go
/kind feature
Check if the error is a  `not found` error when retrieving failed.
Fixes #
```release-note
NONE
```
=> Check if server exist by error code

.github/workflows/ci.yml, .golangci.yml, Makefile, pkg/cloudprovider/huaweicloud/alb.go, pkg/cloudprovider/huaweicloud/alb_connection.go, pkg/cloudprovider/huaweicloud/config.go, pkg/cloudprovider/huaweicloud/elb.go, pkg/cloudprovider/huaweicloud/elb_connection.go, pkg/cloudprovider/huaweicloud/error.go, pkg/cloudprovider/huaweicloud/http.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/nat.go, pkg/cloudprovider/huaweicloud/nat_connections.go, pkg/cloudprovider/huaweicloud/throttle.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Enable GitHubAction

.github/workflows/swr-latest-image.yaml, Makefile
Signed-off-by: changzhen <changzhen5@huawei.com>
/kind cleanup
Setup workflow to publish latest images to SWR.
Fixes #109 
```release-note
NONE
```
```docs
```
=> Setup workflow to publish latest images

.github/workflows/swr-released-image.yaml
Signed-off-by: changzhen <changzhen5@huawei.com>
/kind cleanup
Setup workflow to publish released images to SWR.
Fixes #
```release-note
NONE
```
```docs
```
=> Setup workflow to publish released images

OWNERS
/kind cleanup
This PR put @chengxiangdong on to the owner files.
@chengxiangdong and his team will take responsibility to maintain this project.
Fixes #
```release-note
NONE
```
=> Put chengxiangdong to owner file

hack/pre-run-e2e.sh
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> fix checked parameter name

docs/quick-start-with-local-cluster.md
Fixes #
```release-note
NONE
```
```docs
```
=> Fix a small typo in docs

pkg/cloudprovider/huaweicloud/config.go, pkg/cloudprovider/huaweicloud/testdata/valid-cloud-provider.json
This updates to use new myhuaweicloud url pattern as myhwclouds is deprecated on Huawei Cloud
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Update endpoint from myhwclouds to myhuaweicloud

.github/workflows/ci.yml, hack/pre-run-e2e.sh
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> add E2E test workflow

hack/verify-staticcheck.sh
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> add lint check to verify.sh

pkg/cloudprovider/huaweicloud/alb.go
This fixes the logic of setting EPS id.
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> fix logic issue in alb

.gitignore
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add Emacs and Vim related files to .gitignore

pkg/cloudprovider/huaweicloud/nat.go, pkg/cloudprovider/huaweicloud/nat_connections.go
The url of NAT already updated to v2 on Cloud side, the v2.0 one doesn't work any more.
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> Fix nat gateway type of LoadBalancer

test/e2e/natlbservice_test.go
/kind feature
Fixes #134 
```release-note
NONE
```
```docs
```
=> Add e2e test for dnat loadbalancer

hack/update-gofmt.sh
This helps format codes.
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add update-gofmt.sh

docs/example-manifests/huawei-cloud-controller-manager.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Update manifest for cloud-controller-manager

Makefile
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Optimize Makefiles

hack/pre-run-e2e.sh
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> optimize the image path in pre_run_e2e.sh

.github/workflows/ci.yml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Set up E2E test not to run on forked repositories

examples/loadbalancers/secret.yaml, hack/pre-run-e2e.sh, pkg/cloudprovider/huaweicloud/alb.go, pkg/cloudprovider/huaweicloud/elb.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/nat.go, test/e2e/loadbalancerservice_test.go, test/e2e/natlbservice_test.go
/kind cleanup
I see that the HUAWEI CLOUD authentication credential secret must be created into the namespace of the ELB service, which is not very convenient to use. 
Putting the authentication credential secret in the specified namespace is easier to use.
Fixes #120
```release-note
NONE
```
```docs
```
=> Put the authentication credentials into the specified namespace

go.mod, hack/verify-staticcheck.sh, pkg/cloudprovider/huaweicloud/alb_connection.go, pkg/cloudprovider/huaweicloud/elb_connection.go, pkg/common/common.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> create common functions to make code more readable

pkg/config/loadbalancerconfig_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add test for loadbalancerconfig

pkg/cloudprovider/huaweicloud/elb.go, pkg/cloudprovider/huaweicloud/http.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/nat.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> move the util functions to its own module

pkg/utils/filters_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add test for utils/filters

test/e2e/loadbalancerservice_test.go, test/e2e/suite_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> init VpcOptions in suite_test

pkg/cloudprovider/huaweicloud/elb.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/nat.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/config/loadbalancerconfig.go
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> create a basic top-level object for other providers to extend

pkg/cloudprovider/huaweicloud/elb.go, pkg/cloudprovider/huaweicloud/huaweicloud.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> change "sendEvent" func to a Basic private func

go.mod, go.sum, pkg/cloudprovider/huaweicloud/http.go, pkg/config/config.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/core/hc_http_client.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/ecs/v2/ecs_meta.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/ecs/v2/model/model_list_servers_details_request.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/eip_client.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/eip_invoker.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/eip_meta.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_bw_change_to_period_req.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_bandwidth_to_period_request.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_bandwidth_to_period_response.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_publicip_to_period_request.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_publicip_to_period_response.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_to_period_req.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_show_resources_job_detail_request.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_show_resources_job_detail_response.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_sub_jobs.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_create_loadbalancer_req.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_list_loadbalancers_request.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_list_members_request.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_loadbalancer_resp.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_update_certificate_request_body.go, vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_update_listener_req.go, vendor/modules.txt
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> add user-agent: huaweicloud-kubernetes-ccm to request header

pkg/cloudprovider/huaweicloud/huaweicloud.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> change the event type to normal

pkg/cloudprovider/huaweicloud/huaweicloud.go, test/e2e/loadbalancerservice_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> add shared load balancer and deprecated union

manifests/cloud-config, manifests/huawei-cloud-controller-manager.yaml, manifests/rbac-huawei-cloud-controller-manager.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> add manifests files

pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/config/loadbalancerconfig.go, pkg/config/loadbalancerconfig_test.go, test/e2e/loadbalancerservice_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> update paramters name

pkg/utils/reflects_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add test for utils/reflects

pkg/utils/utils_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add test for utils

pkg/utils/utils_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Update tests for utils pkg

pkg/common/common_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add test for common pkg

pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/utils/mutexkv/mutexkv.go
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> add EndpointSliceListener to update the changed Endpoints to the ELB services

OWNERS
/kind cleanup
This PR put @niuzhenguo to the owner file.
Fixes #
```release-note
NONE
```
```docs
```
=> Put niuzhenguo to owner file

hack/pre-run-e2e.sh, manifests/huawei-cloud-controller-manager.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> add schedule on control-plane

manifests/huawei-cloud-controller-manager.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> add yaml that creates the huawei-cloud-provider namespace

OWNERS
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Sort the list of approvers and reviewers

docs/usage-guide.md
Fix the default value of `kubernetes.io/elb.health-check-flag` to `on'.
Fixes #
```release-note
NONE
```
```docs
```
=> fix default value

.github/workflows/swr-latest-image.yaml, .github/workflows/swr-released-image.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> upgrade go-version to 1.19.x

pkg/cloudprovider/huaweicloud/huaweicloud.go
/kind cleanup
- Remove unimplemented interfaces.
Fixes #
```release-note
NONE
```
```docs
```
=> Remove unimplemented interfaces

README.md, docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md, pkg/cloudprovider/huaweicloud/huaweicloud.go
/kind cleanup
- Update usage example 4.
- Update parameter name `kubernetes.io/elb.health-check-options` -> `kubernetes.io/elb.health-check-option` before release.
Fixes #
```release-note
NONE
```
```docs
```
=> Update parameters name

Makefile, hack/pre-run-e2e.sh
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Use the new registry org: k8s-cloudprovider

docs/create-cloud-config-secret.md, docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md
Fixes #
```release-note
NONE
```
```docs
```
=> fix the link issues

README.md
Fixes #
```release-note
NONE
```
```docs
```
=> Fix docs description

README.md
Fixes #
```release-note
NONE
```
```docs
```
=> Add latest version support for v1.25 and v1.26

docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md
Fixes #
```release-note
NONE
```
```docs
```
=> Fix incorrect parameters and example data in documentation

docs/usage-guide.md, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Add default-tls-container-ref annotation to enable TERMINATED_HTTPS

docs/usage-guide.md, pkg/cloudprovider/huaweicloud/huaweicloud.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> add prefix "elb." to default-tls-container-ref

test/e2e/shared_loadbalancer_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor shared loadbalancer E2E test

pkg/cloudprovider/huaweicloud/instances.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> fix CurrentNodeName to use hostname

docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md, hack/deploy/huawei-cloud-controller-manager.yaml, hack/pre-run-e2e.sh, hack/run-e2e.sh, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/dedicated_elb.go, pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go, pkg/config/loadbalancerconfig.go, pkg/utils/filters.go, pkg/utils/filters_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/dedicated_loadbalancer_test.go
/kind feature
- Add support for dedicated(v3) ELB service.
Fixes #
```release-note
NONE
```
```docs
```
=> Add support for dedicated(v3) ELB service

docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md, hack/deploy/huawei-cloud-controller-manager.yaml, hack/pre-run-e2e.sh, hack/run-e2e.sh, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/dedicated_elb.go, pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go, pkg/config/loadbalancerconfig.go, pkg/utils/filters.go, pkg/utils/filters_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/dedicated_loadbalancer_test.go
/kind feature
Add support for dedicated ELB services for version v1.20.
Fixes #
```release-note
NONE
```
```docs
```
=> Add support for dedicated ELB services for version v1.20

docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md, hack/deploy/huawei-cloud-controller-manager.yaml, hack/pre-run-e2e.sh, hack/run-e2e.sh, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/dedicated_elb.go, pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go, pkg/config/loadbalancerconfig.go, pkg/utils/filters.go, pkg/utils/filters_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/dedicated_loadbalancer_test.go, test/e2e/shared_loadbalancer_test.go
/kind feature
Add support for dedicated ELB services for version v1.20.
Fixes #
```release-note
NONE
```
```docs
```
=> Add support for dedicated ELB services for version v1.21

docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md, hack/deploy/huawei-cloud-controller-manager.yaml, hack/pre-run-e2e.sh, hack/run-e2e.sh, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/dedicated_elb.go, pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go, pkg/config/loadbalancerconfig.go, pkg/utils/filters.go, pkg/utils/filters_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/dedicated_loadbalancer_test.go, test/e2e/shared_loadbalancer_test.go
/kind feature
Add support for dedicated ELB services for version v1.22
Fixes #
```release-note
NONE
```
```docs
```
=> Add support for dedicated ELB services for version v1.22

docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md, hack/deploy/huawei-cloud-controller-manager.yaml, hack/pre-run-e2e.sh, hack/run-e2e.sh, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/dedicated_elb.go, pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go, pkg/config/loadbalancerconfig.go, pkg/utils/filters.go, pkg/utils/filters_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/dedicated_loadbalancer_test.go, test/e2e/shared_loadbalancer_test.go
/kind feature
Add support for dedicated ELB services for version v1.23.
Fixes #
```release-note
NONE
```
```docs
```
=> Add support for dedicated ELB services for version v1.23

docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md, hack/deploy/huawei-cloud-controller-manager.yaml, hack/pre-run-e2e.sh, hack/run-e2e.sh, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/dedicated_elb.go, pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go, pkg/config/loadbalancerconfig.go, pkg/utils/filters.go, pkg/utils/filters_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/dedicated_loadbalancer_test.go, test/e2e/shared_loadbalancer_test.go
/kind feature
Add support for dedicated ELB services for version v1.24.
Fixes #
```release-note
NONE
```
```docs
```
=> Add support for dedicated ELB services for version v1.24

docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md, hack/deploy/huawei-cloud-controller-manager.yaml, hack/pre-run-e2e.sh, hack/run-e2e.sh, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/dedicated_elb.go, pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go, pkg/config/loadbalancerconfig.go, pkg/utils/filters.go, pkg/utils/filters_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/e2e/dedicated_loadbalancer_test.go, test/e2e/shared_loadbalancer_test.go
/kind feature
Add support for dedicated ELB services for version v1.25.
Fixes #
```release-note
NONE
```
```docs
```
=> Add support for dedicated ELB services for version v1.25

pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
/kind bug
Fixes #207
```release-note
NONE
```
```docs
```
=> Fix the issues that the bandwidth name is empty

docs/usage-guide.md, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, test/e2e/dedicated_loadbalancer_test.go, test/e2e/shared_loadbalancer_test.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Add charge mode for EIP bandwidth

README.md, docs/iam-policy.md
Fixes #
```release-note
NONE
```
```docs
```
=> Add IAM policy of Huawei Cloud Kubernetes Cloud Provider

docs/usage-guide.md, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> Fix health check protocol for UDP

docs/huawei-cloud-controller-manager-configuration.md, docs/usage-guide.md, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, test/e2e/shared_loadbalancer_test.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Add annotation to preserve client IP for shared load balancer

pkg/config/loadbalancerconfig.go
/kind cleanup
Fixes #216
```release-note
```
```docs
```
=> Fix typo in loadbalancerconfig.go

docs/huawei-cloud-controller-manager-configuration.md
After modifying the configuration, you need to restart the CCM, supplementary instructions.
Fixes #
```release-note
```
```docs
```
=> Add description: CCM needs to be restarted after modifying the configurations

pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/instances.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/ecs.go, pkg/utils/utils.go, pkg/utils/utils_test.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> Supports cluster node name domain name or private IP

pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go
/kind bug
Fixes #228
```release-note
```
```docs
```
=> fix the issue when EIP is empty

pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/common/common.go
/kind bug
Fixes #231
```release-note
```
```docs
```
=> Fix thread pool issue

pkg/cloudprovider/huaweicloud/huaweicloud.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> Ignore services with empty loadbalancerClass if enabling loadbalancerClass

pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/ecs.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix: query ECS based on Pod HostIP to obtain subnet ID instead of HostName

README.md
A minor grammar suggestion.
Not at all.
=> A minor grammer suggestion

pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/model/elb_meta.go, pkg/cloudprovider/huaweicloud/wrapper/model/model_list_loadbalancers_rsp.go, pkg/cloudprovider/huaweicloud/wrapper/model/model_loadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat: optimize repeatedly specifying EIP use case

docs/huawei-cloud-controller-manager-configuration.md, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/config/loadbalancerconfig.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat: add business-name to isolate ELB instances in multiple clusters

docs/huawei-cloud-controller-manager-configuration.md, pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/model/ecs_meta.go, pkg/cloudprovider/huaweicloud/model/model_list_servers_details_response.go, pkg/cloudprovider/huaweicloud/model/model_server_address.go, pkg/cloudprovider/huaweicloud/model/model_server_detail.go, pkg/cloudprovider/huaweicloud/sharedloadbalancer.go, pkg/cloudprovider/huaweicloud/wrapper/ecs.go, pkg/config/loadbalancerconfig.go, pkg/utils/utils.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat: Add support for querying the primary network

docs/create-cloud-config-secret.md, docs/huawei-cloud-controller-manager-configuration.md, manifests/cloud-config, pkg/cloudprovider/huaweicloud/huaweicloud.go, pkg/cloudprovider/huaweicloud/security_group_listener.go, pkg/cloudprovider/huaweicloud/wrapper/ecs.go, pkg/config/config.go
* already exist nodes in k8s cluster and new node into cluster will be associate by security group id of cloud-config
* deleted nodes from cluster will be disassociate by security group id of cloud-config
> /kind feature
Fixes #
```release-note
```
```docs
```
=> feat(securityGroup): add security group of cloud config

docs/getting-started.md
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind feature
Fixes #
@chengxiangdong 
```release-note
```
```docs
```
=> feat(docs): update markdown file of getting-started

.github/workflows/ci.yml, hack/deploy/huawei-cloud-controller-manager.yaml, hack/pre-run-e2e.sh, hack/run-e2e.sh
Fixes #251
```release-note
```
```docs
```
=> fix E2E workflow

pkg/cloudprovider/huaweicloud/wrapper/ecs.go
/kind bug
Fixes #248
```release-note
```
```docs
```
=> fix the issue that the node cannot be removed after ECS is deleted

README.md, manifests/huawei-cloud-controller-manager-daemonset.yaml, manifests/huawei-cloud-controller-manager-deployment.yaml
Fixes #
```release-note
```
```docs
```
=> update manifests version to v1.26.9

.github/workflows/ci.yml
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> update workflow action version

.github/workflows/ci.yml, .github/workflows/swr-latest-image.yaml, .github/workflows/swr-released-image.yaml
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix: upgrade action version of all workflows
